# Generated by Django 5.2.7 on 2025-10-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_images',
            field=models.JSONField(blank=True, default=list, help_text='List of hero image paths for the slider'),
        ),
    ]
