# Generated by Django 5.2.7 on 2025-11-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gms', '0002_siteconfiguration_hero_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='timezone',
            field=models.CharField(default='UTC', help_text='Site timezone (e.g. Asia/Jakarta)', max_length=50),
        ),
    ]
