# Generated by Django 5.2.7 on 2025-11-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gms', '0003_siteconfiguration_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='timezone',
            field=models.CharField(default='Asia/Jakarta', help_text='Site timezone (e.g. Asia/Jakarta)', max_length=50),
        ),
    ]
