# Generated by Django 5.2.7 on 2025-11-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gms', '0004_alter_siteconfiguration_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='admin_theme',
            field=models.CharField(choices=[('auto', 'Auto (System)'), ('light', 'Light'), ('dark', 'Dark')], default='auto', help_text='Admin panel theme', max_length=20),
        ),
    ]
