# Generated by Django 5.2.7 on 2025-11-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gms', '0005_siteconfiguration_admin_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='admin_color_scheme',
            field=models.CharField(choices=[('blue', 'Blue'), ('purple', 'Purple'), ('green', 'Green'), ('red', 'Red'), ('orange', 'Orange'), ('emerald', 'Emerald'), ('teal', 'Teal'), ('indigo', 'Indigo')], default='purple', help_text='Admin panel color scheme', max_length=20),
        ),
    ]
