# Generated by Django 5.2.7 on 2025-11-01 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gms', '0006_siteconfiguration_admin_color_scheme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='admin_color_scheme',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='admin_theme',
        ),
    ]
