# Generated by Django 5.2.7 on 2025-11-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gms', '0007_remove_siteconfiguration_admin_color_scheme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='event_logos/'),
        ),
    ]
