# Generated by Django 5.2.7 on 2025-11-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gms', '0008_event_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionformat',
            name='format_type',
            field=models.CharField(choices=[('SINGLE_ELIMINATION', 'Single Elimination'), ('DOUBLE_ELIMINATION', 'Double Elimination'), ('LEAGUE', 'League'), ('ROUND_ROBIN', 'Round Robin'), ('SWISS_SYSTEM', 'Swiss System'), ('KNOCKOUT', 'Knockout'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
