# Generated by Django 5.2.7 on 2025-11-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gms', '0010_match_away_team_match_home_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='number_of_clubs',
            field=models.PositiveIntegerField(help_text='Expected number of clubs participating in this competition', null=True, blank=True),
        ),
    ]
