# Generated by Django 5.2.7 on 2025-11-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gms', '0011_auto_20251102_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='number_of_clubs',
            field=models.PositiveIntegerField(default=2, help_text='Expected number of clubs participating in this competition', null=True, blank=True),
        ),
    ]
