# Generated by Django 5.2.7 on 2025-11-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gms', '0012_auto_20251102_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date for the competition matches', null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='frequency_day',
            field=models.CharField(choices=[('WEEKEND', 'Weekend Only'), ('WEEKDAY', 'Weekday Only'), ('ALL_DAYS', 'All Days'), ('CUSTOM', 'Custom Days')], default='ALL_DAYS', help_text='Frequency of competition days (weekend, weekday, all days, or custom)', max_length=20),
        ),
        migrations.AddField(
            model_name='competition',
            name='start_date',
            field=models.DateField(blank=True, help_text='Start date for the competition matches', null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='number_of_clubs',
            field=models.PositiveIntegerField(default=2, help_text='Expected number of clubs participating in this competition'),
        ),
    ]
