# Generated by Django 5.2.7 on 2025-11-03 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gms', '0013_competition_end_date_competition_frequency_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_days', to='gms.competition')),
            ],
            options={
                'verbose_name': 'Custom Day',
                'verbose_name_plural': 'Custom Days',
                'unique_together': {('competition', 'date')},
            },
        ),
    ]
