# Generated by Django 5.2.7 on 2025-11-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gms', '0014_customday'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='clubs_per_group',
            field=models.PositiveIntegerField(blank=True, help_text='Number of clubs per group (only applicable if using league with groups)', null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='is_league_with_groups',
            field=models.BooleanField(default=False, help_text='Check if this competition uses league system with groups'),
        ),
        migrations.AddField(
            model_name='competition',
            name='match_type',
            field=models.CharField(choices=[('CLUB_VS_CLUB', 'Club vs Club'), ('INDIVIDUAL_VS_INDIVIDUAL', 'Individual vs Individual (1vs1)'), ('RACE_TIME', 'Race Time'), ('COMPETITION_POINT', 'Competition Point')], default='CLUB_VS_CLUB', help_text='Type of match for this competition', max_length=30),
        ),
        migrations.AddField(
            model_name='competition',
            name='number_of_groups',
            field=models.PositiveIntegerField(blank=True, help_text='Number of groups in the league system (only applicable if using league with groups)', null=True),
        ),
        migrations.AddField(
            model_name='competitionformat',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('COMING_SOON', 'Coming Soon')], default='ACTIVE', help_text='Status of this competition format', max_length=15),
        ),
        migrations.AddField(
            model_name='match',
            name='group_number',
            field=models.PositiveIntegerField(blank=True, help_text='Group number for matches in league with groups', null=True),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='score',
            field=models.IntegerField(blank=True, help_text='Score in case of individual matches or race times', null=True),
        ),
    ]
