# Generated by Django 5.2.7 on 2025-11-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gms', '0015_competition_clubs_per_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='enrolled_participants',
            field=models.ManyToManyField(blank=True, help_text='Participants enrolled in this competition (for individual competitions)', related_name='enrolled_competitions', to='gms.participant'),
        ),
        migrations.AddField(
            model_name='competition',
            name='number_of_participants',
            field=models.PositiveIntegerField(blank=True, help_text='Expected number of participants in this competition (for individual competitions)', null=True),
        ),
    ]
