# Generated by Django 5.2.7 on 2025-11-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gms', '0016_competition_enrolled_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='participant_type',
            field=models.CharField(choices=[('CLUBS', 'Clubs'), ('PARTICIPANTS', 'Participants')], default='CLUBS', help_text='Type of participants for this competition (Clubs or Participants)', max_length=20),
        ),
        migrations.AlterField(
            model_name='competition',
            name='match_type',
            field=models.CharField(choices=[('1VS1_MATCH', '1vs1 Match'), ('RACE_TIME', 'Race Time'), ('COMPETITION_POINT', 'Competition Point')], default='1VS1_MATCH', help_text='Type of match for this competition', max_length=30),
        ),
        migrations.AlterField(
            model_name='competition',
            name='number_of_clubs',
            field=models.PositiveIntegerField(blank=True, help_text='Expected number of clubs participating in this competition', null=True),
        ),
    ]
