# Generated by Django 5.2.7 on 2025-11-10 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gms', '0017_competition_participant_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customday',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customday',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='match',
            name='is_league_match',
            field=models.BooleanField(default=False, help_text='Whether this is a league match instead of bracket'),
        ),
        migrations.AddField(
            model_name='match',
            name='league_points_away',
            field=models.IntegerField(default=0, help_text='Points awarded to away team in league system'),
        ),
        migrations.AddField(
            model_name='match',
            name='league_points_home',
            field=models.IntegerField(default=0, help_text='Points awarded to home team in league system'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='gms.club'),
        ),
        migrations.AddField(
            model_name='medal',
            name='awarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medal',
            name='awarded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medal',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medals_received', to='gms.participant'),
        ),
        migrations.AddField(
            model_name='standings',
            name='goals_against',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='standings',
            name='goals_for',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='standings',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='enrolled_participants',
            field=models.ManyToManyField(blank=True, related_name='competitions_enrolled', to='gms.participant'),
        ),
        migrations.AlterField(
            model_name='match',
            name='referees',
            field=models.ManyToManyField(blank=True, to='gms.referee'),
        ),
        migrations.AlterField(
            model_name='match',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='score',
            field=models.IntegerField(blank=True, help_text='Score of the match for this club', null=True),
        ),
        migrations.AlterField(
            model_name='medal',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medals_received', to='gms.club'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medals_awarded', to='gms.competition'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medals_awarded', to='gms.event'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='medal_type',
            field=models.CharField(choices=[('GOLD', 'Gold'), ('SILVER', 'Silver'), ('BRONZE', 'Bronze'), ('PARTICIPATION', 'Participation')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='medal',
            unique_together={('competition', 'medal_type', 'club', 'participant')},
        ),
        migrations.AlterUniqueTogether(
            name='standings',
            unique_together={('competition', 'club')},
        ),
    ]
