# Generated by Django 5.2.7 on 2025-11-11 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gms', '0018_customday_description_customday_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
        migrations.AddField(
            model_name='match',
            name='away_participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='gms.participant'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='gms.participant'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches_as_club', to='gms.club'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner_participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches_as_participant', to='gms.participant'),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='gms.participant'),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='gms.club'),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='score',
            field=models.IntegerField(blank=True, help_text='Score of the match for this participant/team', null=True),
        ),
        migrations.AlterField(
            model_name='medal',
            name='awarded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
