# Generated by Django 5.2.7 on 2025-11-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gms', '0019_remove_match_winner_match_away_participant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='sport_type',
            field=models.CharField(choices=[('FOOTBALL', 'Football/Soccer'), ('VOLLEYBALL', 'Volleyball'), ('BASKETBALL', 'Basketball'), ('TENNIS', 'Tennis'), ('BADMINTON', 'Badminton'), ('PETANQUE', 'Petanque'), ('OTHER', 'Other')], default='FOOTBALL', help_text='Type of sport for appropriate statistics labeling (GF/GA/GD for football, SF/SA/SD for volleyball, etc.)', max_length=20),
        ),
    ]
