# Generated by Django 5.2.7 on 2025-11-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gms', '0020_competition_sport_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='has_third_place_match',
            field=models.BooleanField(default=False, help_text='Check if this competition should have a third-place match.'),
        ),
    ]
