"""
Django settings for gms_project project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ

# Initialize environ
env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, []),
    CSRF_TRUSTED_ORIGINS=(list, [])
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Take environment variables from .env file
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env('ALLOWED_HOSTS')

# CSRF trusted origins for production
CSRF_TRUSTED_ORIGINS = env('CSRF_TRUSTED_ORIGINS')


# Application definition

INSTALLED_APPS = [
    'unfold',  # Django admin theme
    'unfold.contrib.filters',  # Optional: for advanced filters
    'unfold.contrib.forms',  # Optional: for enhanced forms
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',  # Django extensions
    'django_htmx',  # Django HTMX integration
    # 'solo',  # Django solo for singleton models - commented out due to dependency issues
    'gms',  # Main GMS app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',  # HTMX middleware
    'gms.middleware.TimezoneMiddleware',  # Timezone middleware
]

ROOT_URLCONF = 'gms_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Add templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'gms.context_processors.site_config',  # Custom context processor for site config
            ],
        },
    },
]

WSGI_APPLICATION = 'gms_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
        'CONN_MAX_AGE': 60,  # Connection pooling
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Jakarta'  # Set according to local timezone

USE_I18N = True

USE_TZ = True

# Security settings
if not DEBUG:
    # Hanya untuk production
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_REDIRECT_EXEMPT = []
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    X_FRAME_OPTIONS = 'DENY'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Additional static files configuration to help with caching issues
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Cache settings
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

if not DEBUG:
    # Production cache settings (Redis or Memcached)
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': env('REDIS_URL', default='redis://127.0.0.1:6379/1'),
        }
    }



# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Unfold settings
UNFOLD = {
    "SITE_TITLE": "GMS Admin",
    "SITE_HEADER": "GMS",
    "SITE_BRAND": "GMS",
    
    "COLORS": {
        "primary": {
            "50": "250 245 255",
            "100": "243 232 255",
            "200": "233 213 255",
            "300": "216 180 254",
            "400": "192 132 252",
            "500": "168 85 247",
            "600": "147 51 234",
            "700": "126 34 206",
            "800": "107 33 168",
            "900": "88 28 135",
            "950": "74 4 106"
        }
    },
    
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Authentication",
                "separator": True,
                "items": [
                    {
                        "title": "Users",
                        "link": "/admin/auth/user/",
                    },
                    {
                        "title": "Groups",
                        "link": "/admin/auth/group/",
                    },
                ],
            },
            {
                "title": "GMS Configuration",
                "separator": True,
                "items": [
                    {
                        "title": "Site Configuration",
                        "link": "/admin/gms/siteconfiguration/",
                    },
                    {
                        "title": "Business Units",
                        "link": "/admin/gms/businessunit/",
                    },
                ],
            },
            {
                "title": "GMS Management",
                "separator": True,
                "items": [
                    {
                        "title": "Events",
                        "link": "/admin/gms/event/",
                    },
                    {
                        "title": "Competitions",
                        "link": "/admin/gms/competition/",
                    },
                    {
                        "title": "Competition Formats",
                        "link": "/admin/gms/competitionformat/",
                    },
                    {
                        "title": "Custom Days",
                        "link": "/admin/gms/customday/",
                    },
                ],
            },
            {
                "title": "Participants & Clubs",
                "separator": True,
                "items": [
                    {
                        "title": "Participants",
                        "link": "/admin/gms/participant/",
                    },
                    {
                        "title": "Clubs",
                        "link": "/admin/gms/club/",
                    },
                    {
                        "title": "Referees",
                        "link": "/admin/gms/referee/",
                    },
                ],
            },
            {
                "title": "Matches & Results",
                "separator": True,
                "items": [
                    {
                        "title": "Matches",
                        "link": "/admin/gms/match/",
                    },
                    {
                        "title": "Match Results",
                        "link": "/admin/gms/matchresult/",
                    },
                    {
                        "title": "Standings",
                        "link": "/admin/gms/standings/",
                    },
                ],
            },
            {
                "title": "Venues & Awards",
                "separator": True,
                "items": [
                    {
                        "title": "Venues",
                        "link": "/admin/gms/venue/",
                    },
                    {
                        "title": "Medals",
                        "link": "/admin/gms/medal/",
                    },
                    {
                        "title": "Disqualifications",
                        "link": "/admin/gms/disqualification/",
                    },
                ],
            },
            {
                "title": "Communications",
                "separator": True,
                "items": [
                    {
                        "title": "Announcements",
                        "link": "/admin/gms/announcement/",
                    },
                ],
            },
        ],
    },
}